
export enum ERROR_MESSAGES {
    "NO_RECORD_FOUND" = "Unfortunately, there are no records available at the moment.",
    "SERVER_ERROR" = "Someting went to be wrong!",
    "POLICY_NOT_FOUND" = "Oops! We couldn't find any records at the moment. Please ensure that the provided information is accurate and try again.",
  }
  
  export enum MODULE_KEYS {
    LEADS = "LEAD|LEAD|LATEST_LEAD_WITHOUT_OPPORTUNITY_STATUS",
    CRS_DRAWS = "CRS DRAWS|CRS DRAWS|LATEST_CRS_DRAWS",
    NOC_CODES = "NOC CODE|NOC CODE|LATEST_NOC_CODES",
    STUDY_PROGRAM = "STUDY PROGRAM|STUDY PROGRAM|LATEST_STUDY_PROGRAM",
  
    COMPANY_INFORMATION = "COMPANY INFORMATION|COMPANY INFORMATION|LATEST_COMPANY_INFORMATION",
  
    CUSTOMERS = "CUSTOMER|CUSTOMER|LATEST_CUSTOMER_PR",
  
    USERS = "USERS|USERS|LATEST_USER",
    USERS_CHANGE_ROLE = "USERS|CHANGE ROLE|CHANGE_ROLE",
    ROLES = "latest_roles",
    SECURITY = "SECURITY|SECURITY|ROLE_MODULE",
    BRANCH = "DATA MANAGEMENT|BRANCH|LATEST_BRANCH"
  
  }
  
  export enum FILE_UPLOAD_KEYS {
    LEAD = "LEAD",
    COMPANY_INFORMATION = "COMPANY_INFORMATION",
    USERS = "USERS",
    DOCUMENT_CHECKLIST = "DOCUMENT_CHECKLIST"
  }