export enum MODULE_KEYS {
    USERS = "USERS_USERS_LATEST_USER",
    CHANGE_ROLE = "USERS_CHANGE ROLE_CHANGE_ROLE",
    USER_PROFILE = "USERS_USER PROFILE_LATEST_USER_PROFILE",
    SECURITY_ROLE = "SECURITY_SECURITY_ROLE_MODULE",
    ROLE_GROUP = "SECURITY_ROLE GROUP_LATEST_ROLE_GROUP",
    BRANCH = "DATA MANAGEMENT_BRANCH_LATEST_BRANCH",
    ZONE = "DATA MANAGEMENT_ZONE_ZONE",
    INVENTORY = "INVENTORY_INVENTORY_LATEST_INVENTORY",
    LATEST_BOOKING = "INVENTORY_BOOKING_LATEST_BOOKING",
    PROPERTY_DETAILS = "PROPERTY_PROPERTY DETAILS_LATEST_PROPERTY_DETAILS",
    PROPERTY_RATING = "PROPERTY_PROPERTY RATINGS_LATEST_PROPERTY_RATING",
    ROOM_REVIEW = "PROPERTY_REVIEW_LATEST_REVIEW",
    ROOM_DETAILS = "ROOM_ROOM DETAILS_LATEST_ROOM_DETAILS",
    CALENDER = "CALENDER_CALENDER_LATEST_CALENDAR",
    FORMULA_MAPPING = "FORMULA_FORMULA MAPPING_LATEST_FORMULA_MAPPING",
    PROMO_CODES = "PROMO CODES_PROMO CODES_LATEST_VOUCHER",
    PROPERTY_AREA = "PROPERTY_PROPERTY AREA_LATEST_LOCATIONS"
}