import { ILoadState } from '@/redux/store.enums'
import type { IProperty, IPropertyState } from './property.types'

export const defaultProperty: IProperty = {
	property_name: "",
	property_details_uuid: "",
	property_details_name: "",
	floor_plan: null,
	property_type: "",
	property_images: [
		{
			album_name: "",
			paths: [],
		},
	],
	property_details_profile_pic: null,
	about_property: "",
	property_place_id: "",
	yt_walkthrough_video: [],
	nearby_places: [],
	nearby_type: "",
	property_rating: "",
	property_address_line_1: "",
	property_address_line_2: "",
	property_city: "",
	property_state: "",
	area: "",
	property_pincode: "",
	property_country: "",
	longitude: "",
	latitude: "",
	amenities: [],
	checkin_time: "",
	checkout_time: "",
	food_and_dinning: [],
	booking_request: 0,
	property_policies: {
		bookingType: "autoConfirmed",
		priceRounding: "none",
		dailyPriceType: "default",
		bookingNearType: "autoConfirmed",
		bookingCutOffHour: 0,
		vatRatePercentage: 0,
		dailyPriceStrategy: "allowLower",
		bookingNearTypeDays: null,
		allowGuestCancellation: {
			type: "never",
		},
	},
	BookingQuestion: {
		order: null,
		usage: "notUsed",
		type: undefined,
	},
	rule_allowed: [],
	rule_not_allowed: [],
	user_name: "",
	user_uuid: "",
	status: "ACTIVE",
	id: "",
	account: "",
	currency: "USD",
	room_name: "",
	slug: "",
	is_pet_friendly: false,
	max_occupancy: 0,
	bedrooms: 0,
	available_beds: 0,
	queen_beds: 0,
	king_beds: 0,
	single_beds: 0,
	double_beds: 0,
	bathroom_full: 0,
	bathroom_half: 0,
	property_subtype: "",
	phone: "",
	mobile: "",
	fax: "",
	email: "",
	web: "",
	contactFirstName: "",
	contactLastName: "",
	checkInEnd: "",
	offerType: "",
	controlPriority: "",
	sellPriority: "",
	bookingPageMultiplier: 1.0,
	permit: "",
	roomChargeDisplay: "",
	templates: [],
	groupKeywords: [],
	bookingRules: [],
	bookingQuestions: [],
	webhooks: [],
	property_highlights: [],
	roomTypes: [],
	room_id: "",
	map: function (
		arg0: (image: any) => void
	): import("react").ReactNode | Iterable<import("react").ReactNode> {
		throw new Error("Function not implemented.");
	},
	nearbyLocations: []
};

export const defaultPropertyState: IPropertyState = {
    property_list: {
        loading: ILoadState.idle,
        data: [],
        count: 0,
        error: null,
    },
    single_property: {
        loading: ILoadState.idle,
        data: defaultProperty,
        error: null,
    },
}
